
project_id = "hrgoxcdixvpmcbfgltea"

[functions]
[functions.generate-insights]
verify_jwt = true

[auth]
enabled = true
site_url = "https://leader-leap.com"
additional_redirect_urls = [
  "http://localhost:8080",
  "https://leader-leap-dashboard.lovable.app",
  "http://localhost:8081",
  "http://localhost:8082",
  "http://localhost:8080/",
  "http://localhost:8081/",
  "http://localhost:8082/",
  "https://leader-leap.com",
  "https://leader-leap.com/",
  "https://leader-leap-dashboard.lovable.app/",
  "https://auth.leader-leap.com/auth/callback",
  "https://auth.leader-leap.com/auth/callback/",
  "https://auth.leader-leap.com/auth/confirm",
  "https://auth.leader-leap.com/auth/confirm/",
  "http://localhost:8082/auth/callback",
  "http://localhost:8082/auth/callback/",
  "http://localhost:8081/auth/callback",
  "http://localhost:8081/auth/callback/",
  "https://7f12c5cc-5c91-4071-abf7-9802cae8c209.lovableproject.com",
  "https://7f12c5cc-5c91-4071-abf7-9802cae8c209.lovableproject.com/auth/callback",
  "https://7f12c5cc-5c91-4071-abf7-9802cae8c209.lovableproject.com/"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 8
password_requirements = ""
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
anon_key = ""
service_role_key = ""

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
